version: '3.7'
services:
  app:
    image: docker.pkg.github.com/yanislav-igonin/inspiro-bot/inspiro-bot:latest
    networks:
      - web
    environment: 
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - IS_WEBHOOK_DISABLED=false
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: on-failure
        window: 10s
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.docker.network: "web"

        traefik.http.services.inspiro-bot.loadbalancer.server.port: ${WEBHOOK_PORT}

        traefik.http.routers.inspiro-bot-secure.entrypoints: "https"
        traefik.http.routers.inspiro-bot-secure.rule: "Host(`${WEBHOOK_HOST}`) && PathPrefix(`${WEBHOOK_PATH}`)"
        traefik.http.routers.inspiro-bot-secure.tls: "true"
        traefik.http.routers.inspiro-bot-secure.service: "inspiro-bot"

networks:
  web:
    driver: overlay
    external: true
